"""Model Registry — declarative catalog of all known models.

Sprint 51 (Amendment 1): Extracted from model_router.py so that adding,
removing, or modifying models never requires touching routing logic.

Amendment 2: Each entry declares its abstract ExecutionCapability set.
The Model Router reasons about capabilities only — never about provider
names or provider-specific attributes.

To add a new model: add one ModelEntry here.  The router never changes.
"""

from __future__ import annotations

from hermes.models.routing_decision import (
    CostTier,
    ExecutionCapability,
    LatencyTier,
    Locality,
    ModelEntry,
)

# Shorthand for cleaner registry entries
_C = ExecutionCapability


DEFAULT_REGISTRY: list[ModelEntry] = [
    # ── Anthropic ─────────────────────────────────────────────────
    ModelEntry(
        id="anthropic--claude-opus-4",
        provider="anthropic",
        name="Claude Opus 4",
        context_window=200_000,
        cost_tier=CostTier.PREMIUM,
        latency_tier=LatencyTier.SLOW,
        locality=Locality.CLOUD,
        supports_tools=True,
        supports_vision=True,
        supports_streaming=True,
        supports_reasoning=True,
        family="claude",
        capabilities=frozenset({
            _C.REASONING,
            _C.LONG_CONTEXT,
            _C.CODE_GENERATION,
            _C.MULTIMODAL,
            _C.STRUCTURED_OUTPUT,
        }),
    ),
    ModelEntry(
        id="anthropic--claude-sonnet-4",
        provider="anthropic",
        name="Claude Sonnet 4",
        context_window=200_000,
        cost_tier=CostTier.HIGH,
        latency_tier=LatencyTier.MEDIUM,
        locality=Locality.CLOUD,
        supports_tools=True,
        supports_vision=True,
        supports_streaming=True,
        supports_reasoning=True,
        family="claude",
        capabilities=frozenset({
            _C.REASONING,
            _C.LONG_CONTEXT,
            _C.CODE_GENERATION,
            _C.MULTIMODAL,
            _C.STRUCTURED_OUTPUT,
        }),
    ),
    ModelEntry(
        id="anthropic--claude-haiku-3.5",
        provider="anthropic",
        name="Claude Haiku 3.5",
        context_window=200_000,
        cost_tier=CostTier.LOW,
        latency_tier=LatencyTier.FAST,
        locality=Locality.CLOUD,
        supports_tools=True,
        supports_vision=True,
        supports_streaming=True,
        supports_reasoning=False,
        family="claude",
        capabilities=frozenset({
            _C.FAST_RESPONSE,
            _C.LOW_COST,
            _C.LONG_CONTEXT,
            _C.CODE_GENERATION,
            _C.MULTIMODAL,
            _C.STRUCTURED_OUTPUT,
        }),
    ),
    # ── OpenAI ────────────────────────────────────────────────────
    ModelEntry(
        id="openai--gpt-4o",
        provider="openai",
        name="GPT-4o",
        context_window=128_000,
        cost_tier=CostTier.HIGH,
        latency_tier=LatencyTier.MEDIUM,
        locality=Locality.CLOUD,
        supports_tools=True,
        supports_vision=True,
        supports_streaming=True,
        supports_reasoning=False,
        family="gpt",
        capabilities=frozenset({
            _C.CODE_GENERATION,
            _C.MULTIMODAL,
            _C.STRUCTURED_OUTPUT,
        }),
    ),
    ModelEntry(
        id="openai--gpt-4o-mini",
        provider="openai",
        name="GPT-4o Mini",
        context_window=128_000,
        cost_tier=CostTier.LOW,
        latency_tier=LatencyTier.FAST,
        locality=Locality.CLOUD,
        supports_tools=True,
        supports_vision=True,
        supports_streaming=True,
        supports_reasoning=False,
        family="gpt",
        capabilities=frozenset({
            _C.FAST_RESPONSE,
            _C.LOW_COST,
            _C.CODE_GENERATION,
            _C.MULTIMODAL,
            _C.STRUCTURED_OUTPUT,
        }),
    ),
    # ── Ollama (local) ────────────────────────────────────────────
    ModelEntry(
        id="ollama--llama3.1-8b",
        provider="ollama",
        name="Llama 3.1 8B",
        context_window=128_000,
        cost_tier=CostTier.FREE,
        latency_tier=LatencyTier.MEDIUM,
        locality=Locality.LOCAL,
        supports_tools=True,
        supports_vision=False,
        supports_streaming=True,
        supports_reasoning=False,
        family="llama",
        capabilities=frozenset({
            _C.LOCAL,
            _C.OFFLINE,
            _C.LOW_COST,
            _C.CODE_GENERATION,
            _C.FAST_RESPONSE,
        }),
    ),
    ModelEntry(
        id="ollama--llama3.1-70b",
        provider="ollama",
        name="Llama 3.1 70B",
        context_window=128_000,
        cost_tier=CostTier.FREE,
        latency_tier=LatencyTier.SLOW,
        locality=Locality.LOCAL,
        supports_tools=True,
        supports_vision=False,
        supports_streaming=True,
        supports_reasoning=False,
        family="llama",
        capabilities=frozenset({
            _C.LOCAL,
            _C.OFFLINE,
            _C.LOW_COST,
            _C.CODE_GENERATION,
            _C.REASONING,
        }),
    ),
    ModelEntry(
        id="ollama--mistral-7b",
        provider="ollama",
        name="Mistral 7B",
        context_window=32_000,
        cost_tier=CostTier.FREE,
        latency_tier=LatencyTier.FAST,
        locality=Locality.LOCAL,
        supports_tools=True,
        supports_vision=False,
        supports_streaming=True,
        supports_reasoning=False,
        family="mistral",
        capabilities=frozenset({
            _C.LOCAL,
            _C.OFFLINE,
            _C.LOW_COST,
            _C.FAST_RESPONSE,
            _C.CODE_GENERATION,
        }),
    ),
    ModelEntry(
        id="ollama--deepseek-r1-8b",
        provider="ollama",
        name="DeepSeek R1 8B",
        context_window=64_000,
        cost_tier=CostTier.FREE,
        latency_tier=LatencyTier.MEDIUM,
        locality=Locality.LOCAL,
        supports_tools=False,
        supports_vision=False,
        supports_streaming=True,
        supports_reasoning=True,
        family="deepseek",
        capabilities=frozenset({
            _C.LOCAL,
            _C.OFFLINE,
            _C.LOW_COST,
            _C.REASONING,
        }),
    ),
    # ── Gemini ────────────────────────────────────────────────────
    ModelEntry(
        id="gemini--gemini-2.5-pro",
        provider="gemini",
        name="Gemini 2.5 Pro",
        context_window=1_000_000,
        cost_tier=CostTier.HIGH,
        latency_tier=LatencyTier.MEDIUM,
        locality=Locality.CLOUD,
        supports_tools=True,
        supports_vision=True,
        supports_streaming=True,
        supports_reasoning=True,
        family="gemini",
        capabilities=frozenset({
            _C.REASONING,
            _C.LONG_CONTEXT,
            _C.CODE_GENERATION,
            _C.MULTIMODAL,
            _C.STRUCTURED_OUTPUT,
        }),
    ),
    ModelEntry(
        id="gemini--gemini-2.5-flash",
        provider="gemini",
        name="Gemini 2.5 Flash",
        context_window=1_000_000,
        cost_tier=CostTier.LOW,
        latency_tier=LatencyTier.FAST,
        locality=Locality.CLOUD,
        supports_tools=True,
        supports_vision=True,
        supports_streaming=True,
        supports_reasoning=False,
        family="gemini",
        capabilities=frozenset({
            _C.FAST_RESPONSE,
            _C.LOW_COST,
            _C.LONG_CONTEXT,
            _C.CODE_GENERATION,
            _C.MULTIMODAL,
            _C.STRUCTURED_OUTPUT,
        }),
    ),
]
